version: '3'

services:
  neo4j:
    image: bitnami/neo4j:latest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      #NEO4J_USERNAME neo4j
      NEO4J_PASSWORD: bitnami
      NEO4J_HOST: localhost
      
      
      